backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"   # où les fichiers seront stockés dans ton repo
public_folder: "/images/uploads" # comment ils seront accessibles depuis le site

collections:
  - name: "test"
    label: "Test"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
