backend:
  name: git-gateway
  branch: main

collections:
  - name: "test"
    label: "Test"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
