backend:
  name: git-gateway
  branch: main
  identity_url: "https://voie-spirituelle.netlify.app/.netlify/identity"
  gateway_url: "https://voie-spirituelle.netlify.app/.netlify/git"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
