backend:
  name: github
  repo: rclaasse/voie-spirituelle   # ton dépôt GitHub
  branch: main                      # ta branche principale

media_folder: "images/uploads"      # où stocker les images
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
